import { Duration, EmptyObject, JsonObject, JsonStringMap, MediaParameters, SequenceNumber, LanguageCode, Uuid } from './core';
import { EventEntities } from './entities';
import { DTMFMessage, PlaybackCompletedMessage, PlaybackStartedMessage } from './voice-bots';

export type MessageBase<Type extends string = string, Parameters extends JsonObject = JsonObject> = { version: '2'; id: Uuid; type: Type; seq: SequenceNumber; parameters: Parameters; };
export type ClientMessageBase<T extends string = string, P extends JsonObject = JsonObject> = MessageBase<T, P> & { serverseq: SequenceNumber; position: Duration; };
export type ServerMessageBase<T extends string = string, P extends JsonObject = JsonObject> = MessageBase<T, P> & { clientseq: SequenceNumber; };
export type CloseReason = 'end' | 'error' | 'disconnect' | 'reconnect';
export type CloseParameters = { reason: CloseReason; };
export type ClosedParameters = EmptyObject;
export type DisconnectReason = 'completed' | 'unauthorized' | 'error';
export type DisconnectParameters = { reason: DisconnectReason; info?: string; outputVariables?: JsonStringMap; };
export type EventParameters = { entities: EventEntities; };
export type Participant = { id: Uuid; ani: string; aniName: string; dnis: string; };
export type OpenParameters = { organizationId: Uuid; conversationId: Uuid; participant: Participant; media: MediaParameters; language?: LanguageCode; customConfig?: JsonObject; inputVariables?: JsonStringMap; };
export type OpenedParameters = { media: MediaParameters; discardTo?: Duration; startPaused?: boolean; };
export type PingParameters = { rtt?: Duration; };
export type PongParameters = EmptyObject;
export type CloseMessage = ClientMessageBase<'close', CloseParameters>;
export type ClosedMessage = ServerMessageBase<'closed', ClosedParameters>;
export type DisconnectMessage = ServerMessageBase<'disconnect', DisconnectParameters>;
export type ErrorMessage = ClientMessageBase<'error', { code: number; message: string; }>;
export type EventMessage = ServerMessageBase<'event', EventParameters>;
export type OpenMessage = ClientMessageBase<'open', OpenParameters>;
export type OpenedMessage = ServerMessageBase<'opened', OpenedParameters>;
export type PingMessage = ClientMessageBase<'ping', PingParameters>;
export type PongMessage = ServerMessageBase<'pong', PongParameters>;
export type ClientMessage = CloseMessage | ErrorMessage | OpenMessage | PingMessage | DTMFMessage | PlaybackStartedMessage | PlaybackCompletedMessage;
export type ServerMessage = ClosedMessage | DisconnectMessage | EventMessage | OpenedMessage | PongMessage;
export type Message = ClientMessage | ServerMessage;
export type ClientMessageType = ClientMessage['type'];
export type ServerMessageType = ServerMessage['type'];
export type SelectParametersForType<T extends string, M> = M extends {type: T, parameters: infer P} ? P : never;
export type SelectMessageForType<T extends string, M> = M extends {type: T} ? M : never;